name: Atualizar site BBM Digital com BotCity

on:
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos (horário UTC)
  push:
    branches:
      - main

jobs:
  atualizar_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Etapa opcional para configurar o BotCity (caso você queira aproveitar funcionalidades extras do bot)
      - name: Configurar BotCity
        uses: botcity-dev/github-action-bot@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar o script de atualização
        run: python3 gerar_html_bbm_paginado.py

      - name: Commit e push de alterações
        run: |
          git config --local user.email "garcia.rodrigo@usp.br"
          git config --local user.name "RodrigoMGarcia"
          git add index.html
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Atualização automática do index.html [skip ci]"
            git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/RodrigoMGarcia/bbm-recent-submissions.git main
          else
            echo "Nenhuma alteração detectada."
          fi
